server:
  error:
    path: /error
    whitelabel:
      enabled: false

logging:
  file:
    path: logs

spring:
  config:
    activate:
      on-profile: local
  main:
    web-application-type: servlet
    # web-application-type: reactive
  output:
    ansi:
      enabled: always
  mvc:
    # Not Found시 exception 발생 여부
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      # 엔드포인트 리소스와 매핑 여부
      add-mappings: false
    servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 100MB
  thymeleaf:
    # thymeleaf 사용 여부
    enabled: true
    # template 경로 접두사
    prefix: classpath:templates/
    # template 경로 접미사
    suffix: .html
    # template 인코딩
    encoding: UTF-8
    #기본 template 모드
    mode: HTML
    # 렌더링 전에 template 존재 여부 확인
    check-template: true
    # template 위치 존재 여부 확인
    check-template-location: true
    # 캐시 사용 여부 확인
    cache: false
  messages:
    basename:
      - classpath:/messages/messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      additional-exclude: component/**, template/**
  security:
    oauth2:
      tenant:
        id: 2002127d-ecd5-424c-b995-a6f750055ecd
      provider:
        microsoft:
          base-url: https://login.microsoftonline.com
          token-url: https://login.microsoftonline.com/${spring.security.oauth2.tenant.id}/oauth2/v2.0/token
          scope: https://graph.microsoft.com/.default
          discovery-url: https://login.microsoftonline.com/${spring.security.oauth2.tenant.id}/discovery/v2.0/keys?appid=${spring.security.oauth2.client.id}
        auth:
          # base-url: http://localhost:10000
          base-url: https://auth-dev.koreazinc.co.kr
          # base-url: https://auth.koreazinc.co.kr
          # authorization-url: http://localhost:10000/v2/oauth/login
          authorization-url: https://auth-dev.koreazinc.co.kr/v2/oauth/login
          # authorization-url: https://auth.koreazinc.co.kr/v2/oauth/login
          # token-url: http://localhost:10000/v2/oauth/token
          token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
          # token-url: https://auth.koreazinc.co.kr/v2/oauth/token
          # user-info-url: http://localhost:10000/v2/user/me
          user-info-url: https://auth-dev.koreazinc.co.kr/v2/user/me
          # user-info-url: https://auth.koreazinc.co.kr/v2/user/me
          # logout-url: http://localhost:10000/v2/oauth/logout
          logout-url: https://auth-dev.koreazinc.co.kr/v2/oauth/logout
          # logout-url: https://auth.koreazinc.co.kr/v2/oauth/logout
          scope: api://278edc9e-5662-4af5-b373-3f59330612e6/.default
        file:
          # base-url: http://localhost:8100
          base-url: https://filesdev.koreazinc.co.kr
          # base-url: https://files.koreazinc.co.kr
          token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
          # scope: api://aed43b32-4829-4a4f-99c6-5edbf251fb9a/.default
          scope: api://8dc5950a-b206-4b65-897c-a04e8fcb193b/.default
          # scope: api://695b70f6-0884-408a-be3c-0f695efd39ab/.default
        message:
          # base-url: http://localhost:15000
          base-url: https://message-api-dev.koreazinc.co.kr
          # base-url: https://message-api.koreazinc.co.kr
          token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
          scope: api://69721da5-1b95-473f-86fe-432c81850063/.default
        hr:
          # base-url: http://localhost:11000
          base-url: https://ehr-api-dev.koreazinc.co.kr
          # base-url: https://ehr-api.koreazinc.co.kr
          token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
          scope: api://c2abd92e-0d00-48b4-967c-f10c575920c8/.default
        gw:
          # base-url: http://localhost:11000
          base-url: https://gw-api-dev.koreazinc.co.kr
          # base-url: https://gw-api.koreazinc.co.kr
          token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
          scope: api://9fe3b276-d24f-432e-ab78-eaafd689b79a/.default
      client:
        redirect:
          login-url: '{URL}/authorize'
          logout-url: '{URL}'