eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: https://eureka-dev.koreazinc.co.kr/eureka
      # defaultZone: https://eureka.koreazinc.co.kr/eureka