server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  devtools: # devtools
    livereload:
      enabled: false
    restart:
      enabled: true

oauth:
  client-id: 79983b8b-d229-4da3-b615-3cc4d23372b5
  login-url: https://auth-dev.koreazinc.co.kr/oauth2/login
  token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
  userinfo-url: https://auth-dev.koreazinc.co.kr/v2/user/me
  redirect-uri: http://localhost:8081/oauth/callback
