server:
  port: 8081
  forward-headers-strategy: framework

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  devtools: # devtools
    livereload:
      enabled: false
    restart:
      enabled: true

oauth:
  client-id: 79983b8b-d229-4da3-b615-3cc4d23372b5
  login-url: https://auth-dev.koreazinc.co.kr/oauth2/login
  token-url: https://auth-dev.koreazinc.co.kr/v2/oauth/token
  userinfo-url: https://auth-dev.koreazinc.co.kr/v2/user/me
  #redirect-uri: http://localhost:8081/oauth/callback
  
---
# [1. 로컬 환경]
spring:
  config:
    activate:
      on-profile: local
oauth:
  redirect-uri: http://localhost:8081/oauth/callback

---
# [2. IP 접속 테스트 환경]
spring:
  config:
    activate:
      on-profile: dev
oauth:
  redirect-uri: http://172.20.27.4:8081/oauth/callback  

logging:
  level:
    root: info
    kr.co.koreazinc: debug         # 내 코드의 로그 출력
    org.springframework.security: debug # 인증/인가 관련 문제 확인 (필수!)
    org.hibernate.SQL: debug       # 실행 SQL 확인